version: '3.3'
services:
### MySQL Container
  auth_db:
    build:
      dockerfile: auth-db.Dockerfile
      args:
        - MYSQL_DATABASE=${AUTH_DB_DATABASE}
        - MYSQL_USER=${AUTH_DB_USER}
        - MYSQL_PASSWORD=${AUTH_DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${AUTH_DB_ROOT_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:3306"
  auth-service:
    build:
      dockerfile: auth-service.Dockerfile