services:
### MySQL Container
  auth-db:
    build:
      dockerfile: auth-db.Dockerfile
      args:
        - MYSQL_DATABASE=${AUTH_DB_DATABASE}
        - MYSQL_USER=${AUTH_DB_USER}
        - MYSQL_PASSWORD=${AUTH_DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${AUTH_DB_ROOT_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:3306"
  auth-service:
  #TODO: Drop env_file
    env_file: .env
    build:
      dockerfile: auth-service.Dockerfile
      args:
        - API_KEY=${AUTH_SERVICE_API_KEY}
        - ADMIN_PASS=${AUTH_SERVICE_ADMIN_PASS}
        - URLS=${AUTH_SERVICE_URLS}
    ports:
      - "5062:5062"